spring:
  cors:
    host: ${SPRING_CORS_HOST}
  application:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description@"
  servlet:
    multipart:
      max-file-size: "50MB"
      max-request-size: "50MB"

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    dbName: ${SPRING_DB_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_VALIDATE}
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  servlet:
    context-path: "/@project.artifactId@"

logging:
    level:
      root: INFO
firebase:
  pathAccountKey: ${FIREBASE_PATH_ACCOUNT_KEY}

springdoc:
  swagger-ui.path: /swagger-ui.html

