
CREATE TABLE pessoas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    contato_telefone VARCHAR(11) NOT NULL,
    tipo_pessoa VARCHAR(31) NOT NULL,
    contato_email VARCHAR(100) NOT NULL,
    nome VARCHAR(100) NOT NULL,
    documento VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE cidadaos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id)
);

CREATE TABLE protocolos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero_protocolo VARCHAR(255) NOT NULL,
    nome_solicitante VARCHAR(100) NOT NULL,
    cpf_cnpj VARCHAR(14) NOT NULL,
    contato_email VARCHAR(100) NOT NULL,
    contato_telefone VARCHAR(11) NOT NULL,
    descricao TEXT NOT NULL,
    endereco_logradouro VARCHAR(100) NOT NULL,
    endereco_numero VARCHAR(10) NOT NULL,
    endereco_complemento VARCHAR(50),
    endereco_bairro VARCHAR(50) NOT NULL,
    endereco_cidade VARCHAR(50) NOT NULL,
    endereco_estado VARCHAR(2) NOT NULL,
    endereco_cep VARCHAR(9) NOT NULL,
    protocolo_status VARCHAR(20) NOT NULL,
    tipo_documento BIGINT NOT NULL,
    criado_em TIMESTAMP(6),
    atualizado_em TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE arquivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    protocolo_id BIGINT,
    nome_original VARCHAR(100) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    tamanho BIGINT NOT NULL,
    conteudo BYTEA NOT NULL,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_protocolo_numero ON protocolos (numero_protocolo);
CREATE UNIQUE INDEX idx_pessoa_email ON pessoas (contato_email);
CREATE UNIQUE INDEX idx_pessoa_documento ON pessoas (documento) WHERE documento IS NOT NULL;

ALTER TABLE usuarios 
    ADD CONSTRAINT FK_usuarios_pessoas 
    FOREIGN KEY (id) 
    REFERENCES pessoas;

ALTER TABLE cidadaos 
    ADD CONSTRAINT FK_cidadaos_usuarios 
    FOREIGN KEY (id) 
    REFERENCES usuarios;

ALTER TABLE arquivos 
    ADD CONSTRAINT FK_arquivos_protocolos 
    FOREIGN KEY (protocolo_id) 
    REFERENCES protocolos;