
name: Deploy Portal WEB

on:
    push:
        branches: [develop]

jobs:           
    deploy:
        runs-on: self-hosted
        steps:
            - name: Excluir codigo antigo
              run: rm -Rf ./portal-cidadao || true

            - name: Checkout code
              uses: actions/checkout@v3
              
