
name: Deploy Portal WEB

on:
    push:
        branches: [develop]

jobs:           
    deploy:
        runs-on: self-hosted
        steps:
            - name: Excluir codigo antigo
              run: rm -Rf ./portal-cidadao || true

            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: Maven setup  
              uses: s4u/setup-maven-action@v1.18.0
              with:
                maven-version: '3.9.9'

            - name: Setup JAVA
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '21'

            - name: Build project
              run: mvn clean install -DskipTests

            - name: Executar migracao
              run:  >
                mvn flyway:migrate
                -Dflyway.user=${{secrets.SPRING_DATASOURCE_USERNAME}}
                -Dflyway.password=${{secrets.SPRING_DATASOURCE_PASSWORD}}
                -Dflyway.schemas=public
                -Dflyway.url=${{secrets.SPRING_DATASOURCE_URL}}
                -Dflyway.locations=filesystem:src/main/resources/db/migration

            - name: Run JAR
              run: >
                java
                  -DSPRING_DATASOURCE_USERNAME=${{secrets.SPRING_DATASOURCE_USERNAME}}
                  -DSPRING_DATASOURCE_PASSWORD=${{secrets.SPRING_DATASOURCE_PASSWORD}}
                  -DFIREBASE_PATH_ACCOUNT_KEY=${{secrets.FIREBASE_PATH_ACCOUNT_KEY}}
                  -DSPRING_CORS_HOST=${{secrets.SPRING_CORS_HOST}}
                  -DSPRING_DATASOURCE_URL=${{secrets.SPRING_DATASOURCE_URL}}
                  -DSPRING_DB_NAME=${{secrets.SPRING_DB_NAME}}
                  -jar target/portal-cidadao-0.0.1.jar