
name: Deploy Portal WEB

on:
    push:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '21'
            
            - name: Build project
              run: mvn clean install -DskipTests
            
            - name: Create Firebase config JSON from Secret
              run: echo '${{ secrets.FIREBASE_ACCOUNT_VALUE }}' > firebase-key.json
            
            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            
            - name: Build docker image
              run: docker build -t eliezertsilva/portal-cidadao .
            
            - name: Push image docker
              run: docker push eliezertsilva/portal-cidadao
              
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              
            - name: Maven setup  
              uses: s4u/setup-maven-action@v1.18.0
              with:
                maven-version: '3.9.9'

            - name: Setup JAVA
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '21'

            - name: Build project
              run: mvn clean install -DskipTests
            - name: Executar migracao
              run:  >
                mvn flyway:migrate
                -Dflyway.user=${{secrets.SPRING_DATASOURCE_USERNAME}}
                -Dflyway.password=${{secrets.SPRING_DATASOURCE_PASSWORD}}
                -Dflyway.schemas=public
                -Dflyway.url=jdbc:postgresql://localhost:5432/protocolo_web_dev
                -Dflyway.locations=filesystem:src/main/resources/db/migration

            - name: Login Docker Hub
              run: sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

            - name: Parar container
              run: sudo docker stop portal-cidadao || true

            - name: Remove docker container
              run: sudo docker rm -f portal-cidadao || true
            
            - name: Remove docker container
              run: sudo docker rmi -f eliezertsilva/portal-cidadao || true

            - name: Pull image from docker hub
              run: sudo docker pull eliezertsilva/portal-cidadao:latest

            - name: Run docker container
              run: >
                sudo docker run -d -p 8080:8080
                -e SPRING_DATASOURCE_USERNAME=${{secrets.SPRING_DATASOURCE_USERNAME}}
                -e SPRING_DATASOURCE_PASSWORD=${{secrets.SPRING_DATASOURCE_PASSWORD}}
                -e SPRING_DATASOURCE_URL=${{secrets.SPRING_DATASOURCE_URL}}
                -e SPRING_DB_NAME=${{secrets.SPRING_DB_NAME}}
                --name portal-cidadao eliezertsilva/portal-cidadao:latest 